version: "3"
services:
  postgres:
    image: postgres:11.6-alpine
    restart: always
    volumes:
      - db_django:/var/lib/postgresql/data
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-djangosecret}
      - VIRTUAL_HOST=${MY_HOST:-example.com}
      - LETSENCRYPT_HOST=${MY_HOST:-example.com}
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver --noreload 0.0.0.0:80"
    depends_on:
      - postgres

volumes:
  db_django:

networks:
  default:
    external:
      name: nginx-proxy
