version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - VIRTUAL_HOST=cookiecutter.skydreamy.com
      - LETSENCRYPT_HOST=cookiecutter.skydreamy.com
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:80"
    volumes:
      - ./:/code
    depends_on:
      - postgres

networks:
  default:
    external:
      name: nginx-proxy
