site_name: djangorestadmin
site_description: Django rest admin cookiecutter test
repo_url: https://github.com/marc-hg/django-rest-admin
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/marc-hg">marc-hg</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
